import boto3
import json
import requests
import time
import logging
from os import getenv

LOGGER = logging.getLogger()
LOGGER.setLevel(logging.ERROR)
CSRF_TOKEN = None


def lambda_handler(event, context):
    global CSRF_TOKEN
    client = boto3.client("appsync")
    as_response = client.create_api_key(
        apiId=getenv("API_ID"),
        description="Autogenerated by appsync-key-rotation 🧙‍♂️",
        expires=int(time.time()) + int(getenv("TTL_SECONDS")),
    )
    key_id = as_response["apiKey"]["id"]

    as_uri = client.get_graphql_api(
        apiId=getenv("API_ID")
    )['graphqlApi']['uris']["GRAPHQL"]

    if not as_uri.lower().startswith("https://"):
        raise Exception(f"GraphQL URI looks broken! - {as_uri}")

    client = boto3.client("secretsmanager")
    secrets = json.loads(
        client.get_secret_value(SecretId=getenv("SECRET"))["SecretString"]
    )

    csrf_resp = requests.post(
        f'{secrets["BASE_URL"]}/bpm/system/login',
        auth=(secrets["BPM_USER"], secrets["BPM_PW"]),
        json={"requested_lifetime": 7200},
    )
    if csrf_resp.status_code != 201:
        raise Exception(
            f"ERROR {csrf_resp.status_code}: Cannot get CSRF token: {csrf_resp.text}"
        )
    CSRF_TOKEN = csrf_resp.json()
    r = requests.post(
        f"{secrets['BASE_URL']}/bpm/processes?model=UpdateEnvironmentVar&container=SPPEU",
        headers={"BPMCSRFToken": CSRF_TOKEN["csrf_token"]},
        auth=(secrets["BPM_USER"], secrets["BPM_PW"]),
        json={
            "input": [
                {
                    "name": "envVarPairs",
                    "data": {"pairs": [{"name": "GRAPHQL_API_KEY", "value": key_id},
                            {"name": "GRAPHQL_SERVER", "value": as_uri}]},
                },
                {
                    "name": "targetContainers",
                    "data": json.loads(getenv("BAW_CONTAINERS")),
                },
                {"name": "defaultOnly", "data": True},
            ]
        },
    )
    if r.status_code != 201:
        raise Exception(r.text)
